// the PROPERTY_LABELS object acts a mapping between model properties and their UI labels
export default {
    acres: "Acres",
    address: "Address",
    association: "Association",
    availability: "Availability",
    blockId: "Block ID",
    city: "City",
    description: "Property Description",
    exteriorPerimeter: "Exterior Perimeter",
    featured: "Featured",
    id: "ID",
    imageUrl: "Image",
    lotId: "Lot ID",
    objectId: "Object ID",
    parkingDescription: "Parking Description",
    pictureOrder: "Picture Order",
    pricePerAcre: "Price Per Acre",
    pricePerSqft: "Price Per Sqft",
    relatedProperties: "Related Properties",
    shapeArea: "Shape Area",
    shapeLength: "Shape Length",
    status: "Status",
    subdivision: "Subdivision",
    totalPrice: "Total Price",
    totalSqft: "Total Square Footage",
    type: "Type",
    utilities: "Utilities Description",
    zip: "Zip Code"
};
