version: '3'

services:
  nginx-php-grav:
    container_name: lwrc-grav
    image: pushhere/nginx-php-grav:1.1.0 # https://hub.docker.com/r/pushhere/nginx-php-grav/
    # Use these properties when testing this repo against locally built images
    # build: ../nginx-php-grav
    # image: nginx-php-grav:local-test
    ports:
      - "2222:22"
      - "80:80"
    volumes:
      - "./grav:/usr/share/nginx/html/"
      - "./nginx:/etc/nginx/"
      - "./.ssh:/root/.ssh/"
