#!/bin/bash


sync_env() {
	rsync -avc push_dev@lc-www1:~/www.lwrcommercial.com/$1/pages ./pages
}


read -p "Are you sure you would like to copy down files from $1? It may change your working copies. [Y/n]" -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
	echo "Pulling down the $1 environment"
	sync_env $1
then
    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1 # handle exits from shell or function but don't exit interactive shell
fi