#!/bin/bash


sync_env() {
    rm -rf ./grav/user/pages
	rsync -avc push_dev@lc-www1:~/www.lwrcommercial.com/$1/grav/user/pages/ ./grav/user/pages
}


read -p "Are you sure you would like to copy down files from $1? It will overwrite your local ./grav/user/pages directory. [Y/n]" -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
	echo "Pulling down the $1 environment"
	sync_env $1
then
    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1 # handle exits from shell or function but don't exit interactive shell
fi