title: 'Lakewood Ranch Commercial'
default_lang: en
author:
  name: 'Push Admin'
  email: dev+lwrc@pushhere.com
taxonomies:
  - category
  - tag
metadata:
  description: 'update meta description'
  gtm-id: GTM-NBNH6NN
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
routes:
  '/property-detail/(.*)': /property-detail
blog:
  route: /press
