#!/bin/bash
source $HOME/.bash_profile

function string_replace {
    echo "${1/\*/$2}"
}

while read oldrev newrev refname; do FILES_CHANGED+=`git diff --name-only $oldrev..$newrev | awk 'NR > 1 { printf(", ") } { printf("%s%s", $1, $2) }'`; done

CURRENT=`pwd`
BASENAME=`basename "$CURRENT"`
LC_BASENAME=$(echo $BASENAME | awk '{print tolower($0)}')
APP_ENV=$(echo $LC_BASENAME | sed 's/.git//g')
echo "Application Environment Detected: $APP_ENV"

# update this <environment> placeholder for the environment this hook is configured for
target=$HOME/www.lwrcommercial.com/<environment>
grav_user=$target/grav/user

echo "Deploying $newrev to $target..."
GIT_WORK_TREE=$target git checkout -f

cd $target
./scripts/build.sh "$FILES_CHANGED" "$APP_ENV"